"""
Django settings for E_commerce project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from .settings_email import *


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-=(xfqe+cmn83d!mj62xdz!s2jod_48b5nvrr)0_ap#yp3mqa)a'
os.environ.get('SECRET_KEY', 'dev-only-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [".hf.space",]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'commerce_shop',
    'e_commerce_account',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    "corsheaders",      # 新增 CORS 支援
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# E-Mail

# Email 設定（開發用）
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'E_commerce.email_backend.ReadableConsoleEmailBackend'
ACCOUNT_ADAPTER = 'e_commerce_account.adapters.MyAccountAdapter'
DEFAULT_FROM_EMAIL = 'admin@example.com'
EMAIL_CHARSET = 'utf-8'

# 關閉 Email 驗證（開發用）
ACCOUNT_EMAIL_VERIFICATION = "optional" # <== 用 none 不會寄信
# ACCOUNT_EMAIL_REQUIRED = False 已過時的設定

# allauth 設定
#ACCOUNT_USER_MODEL_USERNAME_FIELD = None          # 不使用 username
#ACCOUNT_USERNAME_REQUIRED = False 已過時的設定
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

# 綠界測試環境
ECPAY_MERCHANT_ID = "3002607"
ECPAY_HASH_KEY = "pwFHCqoQZGmho4w6"
ECPAY_HASH_IV = "EkRm7iFT261dpevs"


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 放在最前面
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'E_commerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'E_commerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"   # 加這行

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# -------------------------------
# 🔑 CORS & CSRF 設定
# -------------------------------

# 允許跨域來源 (前端網址)
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
	"https://hf.space",
#	"https://huggingface.co/spaces/monzid1-ecommerce.hf.space",
#	"https://huggingface.co/spaces/monzid1-ecpay-mock.hf.space",
#	"https://huggingface.co/spaces/monzid1-bank-site.hf.space",
#    "http://127.0.0.1:8001",   # React/Vue 本地端 3000
#    "http://localhost:8001",
]

# 如果要允許所有來源 (開發用)
# CORS_ALLOW_ALL_ORIGINS = False

# 允許跨域攜帶 Cookie
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = True

# CSRF 白名單 (允許的前端來源)
CSRF_TRUSTED_ORIGINS = [
	"https://hf.space",
#	"https://huggingface.co/spaces/monzid1-ecommerce.hf.space",
#	"https://huggingface.co/spaces/monzid1-ecpay-mock.hf.space",
#	"https://huggingface.co/spaces/monzid1-bank-site.hf.space",
#    "http://127.0.0.1:8001",
#    "http://localhost:8001",
]
