# Generated by Django 6.0.3 on 2026-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_shop', '0003_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cateId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
